# используем язык java. Travis CI поддерживает другие языки тоже.
language:
  java
jdk:
  openjdk11
# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
- bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту gtb-85@yandex.ru если сборка упала
notifications:
  email:
    recipients:
      gtb-85@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always

env:
  global:
    CODECOV_TOKEN="5c4947e7-e408-4f18-b3b9-81d82c738487"